CABECALHO = "C"
DADOS = "D"
SECCIONAMENTO = "S"
ENDERECO = "E"
PATH = "/home/anderson/workspaceConsultaCep/DADOSCEP/eDNE_Basico_1502/Fixo/{}"

MAPLOGRADOURO = {CABECALHO:
                     [{'separador': 1},
                      {'versao': 5},
                      {'separador': 2},
                      {'diaGravacao': 2},
                      {'separador': 1},
                      {'mesGravacao': 3},
                      {'separador': 1},
                      {'anoGravacao': 4},
                      {'separador': 4},
                      {'informacaoAutoria': 11},
                      {'separador': 1},
                      {'identificacaoAutor', 8},
                      {'separador': 17},
                      {'descricao': 11}],
                 DADOS:
                     [{'sigla': 2},
                      {'separador': 6},
                      {'chaveLocalidade': 8},
                      {'nomeOficialLocalidade': 72},
                      {'separador': 5},
                      {'chaveBairro': 8},
                      {'bairroInicial': 72},
                      {'separador': 5},
                      {'chaveBairroFinal': 8},
                      {'bairroFinal': 72},
                      {'tipoOficialLogradouro': 26},
                      {'preposicao': 3},
                      {'patenteOficial': 72},
                      {'separador': 6},
                      {'chaveLogradouro': 8},
                      {'nomeOficial': 72},
                      {'abreviaturaLogradouro': 36},
                      {'informacaoAdicional': 36},
                      {'cep': 8},
                      {'indicadorGrandeUsuario': 1},
                      {'tipoLogradouroAtivo': 1}],
                 SECCIONAMENTO:
                     [{'sigla': 2},
                      {'separador': 6},
                      {'chaveLocalidade': 8},
                      {'nomeOficialLocalidade': 72},
                      {'separador': 5},
                      {'chaveBairro': 8},
                      {'bairroInicial': 72},
                      {'separador': 5},
                      {'chaveBairroFinal': 8},
                      {'bairroFinal': 72},
                      {'tipoOficialLogradouro': 26},
                      {'preposicao': 3},
                      {'patenteOficial': 72},
                      {'separador': 6},
                      {'chaveLogradouro': 8},
                      {'nomeOficial': 72},
                      {'abreviaturaLogradouro': 36},
                      {'informacaoAdicional': 36},
                      {'cep': 8},
                      {'indicadorGrandeUsuario': 1},
                      {'numeroInicialTrecho': 11},
                      {'numeroFinaltrecho': 11},
                      {'identificacaoParidade': 1},
                      {'chaveSeccionamento': 8},
                      {'tipoLogradouroAtivo': 1}]}

MAPLOCALIDADE = {CABECALHO:
                  [{'separador': 1},
                   {'versao': 5},
                   {'separador': 2},
                   {'diaGravacao': 2},
                   {'separador': 1},
                   {'mesGravacao': 3},
                   {'separador': 1},
                   {'anoGravacao': 4},
                   {'separador': 4},
                   {'informacaoAutoria': 11},
                   {'separador': 1},
                   {'identificacaoAutor', 8},
                   {'separador': 17},
                   {'descricao': 11}],
                 DADOS:
                  [{'siglaPais': 2},
                   {'siglaUF': 2},
                   {'separador': 6},
                   {'chave': 8},
                   {'nomeOficial': 72},
                   {'cep': 8},
                   {'abreviaturaLogradouro': 36},
                   {'tipoLocalidade': 1},
                   {'situacaoLocalidade': 1},
                   {'separador': 6},
                   {'chaveSubordinacao': 8},
                   {'siglaDRLocalidade': 3},
                   {'codigoIBGE': 7}]}


MAPABAIRROS = {CABECALHO:
                  [{'separador': 1},
                   {'versao': 5},
                   {'separador': 2},
                   {'diaGravacao': 2},
                   {'separador': 1},
                   {'mesGravacao': 3},
                   {'separador': 1},
                   {'anoGravacao': 4},
                   {'separador': 4},
                   {'informacaoAutoria': 11},
                   {'separador': 1},
                   {'identificacaoAutor', 8},
                   {'separador': 17},
                   {'descricao': 7}],
              DADOS:
                  [{'sigla': 2},
                   {'separador': 6},
                   {'chaveLocalidade': 8},
                   {'nomeOficialLocalidade': 72},
                   {'separador': 5},
                   {'chave': 8},
                   {'nomeOficial': 72},
                   {'abreviatura': 36}]}
